### ISSUE TITLE
Criação da Interface de Login

### ISSUE THREAD

**Issue by zjefersound** [zjefersound/agorium#10]
# Criação da tela de login

**⚠Apenas visual por enquanto, pode deixar um alert("login") ao enviar**

Crie a page `Login` de acordo com as [especificações visuais](https://www.figma.com/design/jIUV83hfRi71MMvYTA6WUe/AGORIUM?node-id=257-4105&t=5kjuI4SMAoUweZsG-0)

Se precisar saber quais componentes já existem veja a [documentação do react-essentials](https://react-essentials-opal.vercel.app/)

**Comment by gabrielmarafon** [comment]
Task completed.
