### ISSUE TITLE
Criação da tela de cadastro

### ISSUE THREAD

**Issue by zjefersound** [zjefersound/agorium#11]
# Criação da tela de cadastro

Crie a page `Signup` de acordo com as [especificações visuais](https://www.figma.com/design/jIUV83hfRi71MMvYTA6WUe/AGORIUM?node-id=275-4136&t=5kjuI4SMAoUweZsG-0)

Se precisar saber quais componentes já existem veja a [documentação do react-essentials](https://react-essentials-opal.vercel.app/)

**Comment by gabrielmarafon** [comment]
Task complete.
